install.packages("devtools")
install.packages("base64enc")
library(devtools)
install_github('ramnathv/rCharts')
library(knitr)
library(rCharts)
require(base64enc)
dt <- dTable(iris, sPaginationType="full_numbers")
dt$save('rChart1.html', standalone=TRUE)
